package tokenizer;
public enum TokenType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, COLON, SLASH, STAR, SHIFT_LEFT, SHIFT_RIGHT, INCREMENT, DECREMENT,POWER,
    MINUS_EQUAL, PLUS_EQUAL, SLASH_EQUAL, STAR_EQUAL, SHIFT_LEFT_EQUAL,SHIFT_RIGHT_EQUAL,
    LEFT_BRACKET, RIGHT_BRACKET,
    // One or two character tokens.
    BANG, BANG_EQUAL,
    QUESTION_MARK,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    // Literals.
    IDENTIFIER, STRING, NUMBER,CHARACTER,
    // Errors
    TRY, CATCH,FINALLY,
    // Keywords.
    AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR,
    PRINT, RETURN, SUPER, THIS, TRUE, CONST, VAR, WHILE, BREAK, CONTINUE,
    EOF
}